import { select, confirm, checkbox, input } from '@inquirer/prompts';
import { resolve } from 'path';
import { cwd } from 'process';

import { print } from '../ui.js';
import {
  loadGlobalConfig,
  saveGlobalConfig,
  loadLocalConfig,
  saveLocalConfig,
  globalConfigExists,
} from '../config.js';

// ─── field definitions ────────────────────────────────────────────────────────

const FIELDS = [
  { key: 'fileTypes',    label: 'File types'    },
  { key: 'debounce',     label: 'Commit delay'  },
  { key: 'pushInterval', label: 'Push interval' },
  { key: 'branchMode',   label: 'Branch mode'   },
];

// ─── field editors ────────────────────────────────────────────────────────────

async function editField(key, currentValue) {
  if (key === 'fileTypes') {
    return checkbox({
      message: 'Which file types should gitwrit watch?',
      choices: [
        { name: '.md',  value: '.md',  checked: currentValue.includes('.md')  },
        { name: '.mdx', value: '.mdx', checked: currentValue.includes('.mdx') },
        { name: '.txt', value: '.txt', checked: currentValue.includes('.txt') },
        { name: '.rst', value: '.rst', checked: currentValue.includes('.rst') },
      ],
    });
  }

  if (key === 'debounce') {
    const choice = await select({
      message: 'How long should gitwrit wait after a save before committing?',
      choices: [
        { name: '3 seconds  (recommended)', value: 3000  },
        { name: '5 seconds',                value: 5000  },
        { name: '10 seconds',               value: 10000 },
        { name: 'Custom',                   value: 'custom' },
      ],
      default: currentValue,
    });
    if (choice === 'custom') {
      const raw = await input({ message: 'Seconds to wait:' });
      return parseFloat(raw) * 1000;
    }
    return choice;
  }

  if (key === 'pushInterval') {
    const choice = await select({
      message: 'How often should gitwrit push to remote?',
      choices: [
        { name: 'Every 5 minutes  (recommended)', value: 300000  },
        { name: 'Every 10 minutes',               value: 600000  },
        { name: 'Every 30 minutes',               value: 1800000 },
        { name: 'Custom',                         value: 'custom' },
      ],
      default: currentValue,
    });
    if (choice === 'custom') {
      const raw = await input({ message: 'Minutes between pushes:' });
      return parseFloat(raw) * 60000;
    }
    return choice;
  }

  if (key === 'branchMode') {
    return select({
      message: 'Default branch mode?',
      choices: [
        { name: "Current branch   — commit to whatever branch you're on", value: 'current'       },
        { name: 'Autogenerated    — create a fresh named branch each session',  value: 'autogenerated' },
      ],
      default: currentValue,
    });
  }
}

// ─── format a setting value for display ───────────────────────────────────────

function formatValue(key, value) {
  if (key === 'fileTypes')    return value.join(', ');
  if (key === 'debounce')     return `${value / 1000}s after last save`;
  if (key === 'pushInterval') return `Every ${value / 60000} min`;
  if (key === 'branchMode')   return value;
  return String(value);
}

// ─── global config flow ───────────────────────────────────────────────────────

async function configureGlobal() {
  print.divider('Global defaults');
  print.gap();

  const config = await loadGlobalConfig();

  for (const { key, label } of FIELDS) {
    print.row(label, formatValue(key, config[key]));
  }

  print.gap();

  const field = await select({
    message: 'Which setting would you like to change?',
    choices: [
      ...FIELDS.map(f => ({ name: f.label, value: f.key })),
      { name: 'Done', value: null },
    ],
  });

  if (!field) return;

  const newValue = await editField(field, config[field]);
  config[field] = newValue;
  await saveGlobalConfig(config);

  print.gap();
  print.good('Global defaults updated.');
  print.hint('Directories without local overrides will use these settings.');

  print.gap();
  const again = await confirm({ message: 'Change another setting?', default: false });
  if (again) await configureGlobal();
}

// ─── local config flow ────────────────────────────────────────────────────────

async function configureLocal(dir) {
  print.divider(`${dir}  — local config`);
  print.gap();

  const global = await loadGlobalConfig();
  const local  = await loadLocalConfig(dir) || {};
  const hasOverrides = Object.keys(local).length > 0;

  for (const { key, label } of FIELDS) {
    const isOverridden = key in local;
    const value = isOverridden ? local[key] : global[key];
    const tag   = isOverridden ? 'local override ✎' : 'global';
    print.row(label, formatValue(key, value), tag);
  }

  print.gap();

  if (!hasOverrides) {
    print.info('This directory is following all global defaults.');
    print.gap();

    const wantsOverride = await confirm({
      message: 'Set a local override?',
      default: false,
    });
    if (!wantsOverride) return;
  }

  const action = hasOverrides
    ? await select({
        message: 'What would you like to do?',
        choices: [
          { name: 'Edit an override',     value: 'edit'   },
          { name: 'Remove an override',   value: 'remove' },
          { name: 'Add another override', value: 'add'    },
        ],
      })
    : 'add';

  if (action === 'edit' || action === 'add') {
    const overriddenKeys = Object.keys(local);
    const choices = action === 'edit'
      ? FIELDS.filter(f => overriddenKeys.includes(f.key))
      : FIELDS.filter(f => !overriddenKeys.includes(f.key));

    if (choices.length === 0) {
      print.hint('Nothing to edit.');
      return;
    }

    const field = await select({
      message: 'Which setting?',
      choices: choices.map(f => ({ name: f.label, value: f.key })),
    });

    const currentValue = local[field] ?? global[field];
    const newValue = await editField(field, currentValue);
    local[field] = newValue;
    await saveLocalConfig(dir, local);
    print.gap();
    print.good('Local override saved.');
  }

  if (action === 'remove') {
    const overriddenKeys = Object.keys(local);
    const field = await select({
      message: 'Which override would you like to remove?',
      choices: FIELDS
        .filter(f => overriddenKeys.includes(f.key))
        .map(f => ({ name: f.label, value: f.key })),
    });

    delete local[field];
    await saveLocalConfig(dir, local);
    print.gap();
    print.good(`Local override for "${field}" removed — reverting to global default.`);
  }

  print.gap();
  const again = await confirm({ message: 'Make another change?', default: false });
  if (again) await configureLocal(dir);
}

// ─── main ─────────────────────────────────────────────────────────────────────

export async function config() {
  if (!(await globalConfigExists())) {
    print.gap();
    print.bad('gitwrit is not set up yet.');
    print.hint('Run gitwrit init first.');
    print.gap();
    return;
  }

  const dir = resolve(cwd());

  print.gap();

  const scope = await select({
    message: 'What would you like to configure?',
    choices: [
      { name: 'Global defaults',          value: 'global' },
      { name: `This directory  (${dir})`, value: 'local'  },
    ],
  });

  print.gap();

  if (scope === 'global') {
    await configureGlobal();
  } else {
    await configureLocal(dir);
  }

  print.gap();
}
