import { spawn } from 'child_process';
import { writeFile, mkdir, readFile } from 'fs/promises';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

import { print } from '../ui.js';
import { PID_FILE, GITWRIT_DIR } from '../paths.js';
import { globalConfigExists, loadGlobalConfig } from '../config.js';
import { readState, STATE } from '../state.js';
import { generateBranchName } from '../expansions.js';

const DAEMON_SCRIPT = join(dirname(fileURLToPath(import.meta.url)), '../daemon.js');

// ─── random start messages ────────────────────────────────────────────────────

const START_MESSAGES = [
  'Type all you want, we\'ve got you.',
  'Happy writing!',
  'Feel free to type away!',
];

function randomStartMessage() {
  return START_MESSAGES[Math.floor(Math.random() * START_MESSAGES.length)];
}

// ─── stale pid check ──────────────────────────────────────────────────────────

async function getLivePid() {
  try {
    const raw = await readFile(PID_FILE, 'utf8');
    const pid = parseInt(raw.trim(), 10);
    if (isNaN(pid)) return null;
    process.kill(pid, 0);
    return pid;
  } catch {
    return null;
  }
}

// ─── main ─────────────────────────────────────────────────────────────────────

export async function start() {
  if (!(await globalConfigExists())) {
    print.gap();
    print.bad('gitwrit is not set up yet.');
    print.hint('Run gitwrit init in a directory to get started.');
    print.gap();
    return;
  }

  const config = await loadGlobalConfig();

  if (config.watch.length === 0) {
    print.gap();
    print.bad('No directories registered.');
    print.hint('Run gitwrit init in a directory to register it.');
    print.gap();
    return;
  }

  const livePid = await getLivePid();
  if (livePid) {
    print.gap();
    print.bad(`gitwrit is already running. (PID ${livePid})`);
    print.hint('Use gitwrit stop to stop it first.');
    print.gap();
    return;
  }

  const state = await readState();
  const wasUnclean = state.status === STATE.PAUSED || state.status === STATE.RUNNING;

  let sessionBranch = null;
  if (config.branchMode === 'autogenerated') {
    sessionBranch = await generateBranchName();
  }

  await mkdir(GITWRIT_DIR, { recursive: true });

  const daemon = spawn(process.execPath, [DAEMON_SCRIPT], {
    detached: true,
    stdio: 'ignore',
    env: {
      ...process.env,
      GITWRIT_SESSION_BRANCH: sessionBranch || '',
    },
  });

  daemon.unref();

  await writeFile(PID_FILE, String(daemon.pid), 'utf8');

  await new Promise(r => setTimeout(r, 300));

  print.gap();

  if (wasUnclean) {
    print.brand('gitwrit is running — picked up where you left off.');
  } else {
    print.brand('gitwrit is running.');
  }

  print.gap();
  print.row('Watching',    config.watch.map(w => w.path).join(', '));
  print.row('Files',       config.fileTypes.join(', '));

  if (sessionBranch) {
    print.row('Branch', sessionBranch, 'autogenerated');
  } else {
    print.row('Branch', 'Current branch');
  }

  print.row('Committing', `${config.debounce / 1000}s after last save`);
  print.row('Pushing',    `Every ${config.pushInterval / 60000} min`);
  print.gap();
  print.hint(randomStartMessage());
  print.gap();
}
