import { checkbox, select, confirm, input } from '@inquirer/prompts';
import { mkdir } from 'fs/promises';
import { resolve } from 'path';
import { cwd } from 'process';

import { print } from '../ui.js';
import {
  DEFAULTS,
  globalConfigExists,
  loadGlobalConfig,
  saveGlobalConfig,
  addWatchPath,
} from '../settings.js';
import { GITWRIT_DIR } from '../paths.js';
import { isGitRepo, hasRemote } from '../git.js';

// ─── main ─────────────────────────────────────────────────────────────────────

export async function init() {
  const dir = resolve(cwd());
  const isFirstRun = !(await globalConfigExists());

  // ── first-run: global setup ────────────────────────────────────────────────

  if (isFirstRun) {
    print.brand("Welcome to gitwrit. Let's get you set up.");
    print.gap();
    print.divider('Global defaults');
    print.hint('These apply to every directory you watch.');
    print.gap();

    await mkdir(GITWRIT_DIR, { recursive: true });

    const fileTypes = await checkbox({
      message: 'Which file types should gitwrit watch?',
      choices: [
        { name: '.md',   value: '.md',   checked: true },
        { name: '.mdx',  value: '.mdx',  checked: true },
        { name: '.txt',  value: '.txt',  checked: false },
        { name: '.rst',  value: '.rst',  checked: false },
      ],
    });

    const debounceChoice = await select({
      message: 'How long should gitwrit wait after a save before committing?',
      choices: [
        { name: '3 seconds  (recommended)', value: 3000 },
        { name: '5 seconds',                value: 5000 },
        { name: '10 seconds',               value: 10000 },
        { name: 'Custom',                   value: 'custom' },
      ],
    });

    let debounce = debounceChoice;
    if (debounceChoice === 'custom') {
      const raw = await input({ message: 'Seconds to wait after a save:' });
      debounce = parseFloat(raw) * 1000;
    }

    const pushChoice = await select({
      message: 'How often should gitwrit push to remote?',
      choices: [
        { name: 'Every 5 minutes  (recommended)', value: 300000 },
        { name: 'Every 10 minutes',               value: 600000 },
        { name: 'Every 30 minutes',               value: 1800000 },
        { name: 'Custom',                         value: 'custom' },
      ],
    });

    let pushInterval = pushChoice;
    if (pushChoice === 'custom') {
      const raw = await input({ message: 'Minutes between pushes:' });
      pushInterval = parseFloat(raw) * 60000;
    }

    const branchMode = await select({
      message: 'Default branch mode?',
      choices: [
        {
          name: "Current branch   — commit to whatever branch you're on",
          value: 'current',
        },
        {
          name: 'Autogenerated    — create a fresh named branch each session  (e.g. crimson-walrus-stumbling)',
          value: 'autogenerated',
        },
      ],
    });

    const globalConfig = {
      ...DEFAULTS,
      fileTypes,
      debounce,
      pushInterval,
      branchMode,
      watch: [],
    };

    await saveGlobalConfig(globalConfig);
    print.gap();
    print.good('Global defaults saved.');
  }

  // ── register current directory ────────────────────────────────────────────

  print.gap();
  print.divider(`Registering ${dir}`);
  print.gap();

  // hard gate: must be a git repo
  const repoValid = await isGitRepo(dir);
  if (!repoValid) {
    print.bad(`${dir} is not a Git repo.`);
    print.hint('Run git init here first, then run gitwrit init again.');
    print.gap();
    process.exit(1);
  }

  // hard gate: must have a remote
  const remoteValid = await hasRemote(dir);
  if (!remoteValid) {
    print.bad('No Git remote configured.');
    print.hint('gitwrit pushes your work to a remote repository to keep it safe.');
    print.hint('Add one first:  git remote add origin <url>');
    print.hint('Then run gitwrit init again.');
    print.gap();
    process.exit(1);
  }

  print.good('Valid Git repo found.');
  print.good('Remote origin configured.');
  print.gap();

  // local overrides — only ask if not first run (first run just inherits global)
  let useGlobalDefaults = true;
  if (!isFirstRun) {
    useGlobalDefaults = await confirm({
      message: 'Use global defaults for this directory?',
      default: true,
    });
  }

  if (!useGlobalDefaults) {
    print.hint('Local overrides can be set anytime with gitwrit config.');
  }

  // register the directory in global watch list
  const added = await addWatchPath({ type: 'directory', path: dir });

  print.gap();

  if (!added) {
    print.warn(`${dir} is already in your watch list.`);
    print.gap();
    return;
  }

  // ── confirmation summary ───────────────────────────────────────────────────

  const config = await loadGlobalConfig();

  print.brand(isFirstRun ? 'All set.' : `${dir} added.`);
  print.gap();
  print.row('Watching',   dir);
  print.row('Files',      config.fileTypes.join(', '));
  print.row('Branch',     config.branchMode);
  print.row('Committing', `${config.debounce / 1000}s after last save`);
  print.row('Pushing',    `Every ${config.pushInterval / 60000} min`);
  print.gap();
  print.hint("Run gitwrit start whenever you're ready.");
  print.gap();
}
