import { readFile } from 'fs/promises';
import { print, timeAgo } from '../ui.js';
import { PID_FILE } from '../paths.js';
import { readState, STATE } from '../state.js';
import { loadGlobalConfig, globalConfigExists } from '../settings.js';

async function getLivePid() {
  try {
    const raw = await readFile(PID_FILE, 'utf8');
    const pid = parseInt(raw.trim(), 10);
    process.kill(pid, 0);
    return pid;
  } catch {
    return null;
  }
}

function formatUptime(startedAt) {
  if (!startedAt) return 'Unknown';
  const seconds = Math.floor((Date.now() - new Date(startedAt)) / 1000);
  if (seconds < 60)   return `${seconds}s`;
  if (seconds < 3600) return `${Math.floor(seconds / 60)}m`;
  return `${Math.floor(seconds / 3600)}h ${Math.floor((seconds % 3600) / 60)}m`;
}

export async function status() {
  if (!(await globalConfigExists())) {
    print.gap();
    print.brand('gitwrit is not set up.');
    print.hint('Run gitwrit init to get started.');
    print.gap();
    return;
  }

  const pid = await getLivePid();
  const state = await readState();
  const config = await loadGlobalConfig();

  print.gap();

  if (!pid) {
    if (state.status === STATE.PAUSED) {
      print.brand('gitwrit is paused.');
      print.gap();
      print.info(`Resumed from sleep — last active ${timeAgo(state.pausedAt)}.`);
      print.gap();
      print.hint('Run gitwrit start to resume watching.');
    } else {
      print.brand('gitwrit is not running.');
      print.hint('Run gitwrit start to begin watching.');
    }
    print.gap();
    return;
  }

  const resumedAfterSleep = state.resumedAt &&
    (Date.now() - new Date(state.resumedAt)) < 60000;

  if (resumedAfterSleep) {
    print.brand('gitwrit is running — resumed after sleep.');
  } else {
    print.brand('gitwrit is running.');
  }

  print.gap();
  print.row('Uptime',      formatUptime(state.startedAt));
  print.row('Watching',    config.watch.map(w => w.path).join(', '));

  if (state.sessionBranch) {
    print.row('Branch', state.sessionBranch, 'autogenerated');
  } else {
    print.row('Branch', 'Current branch');
  }

  if (state.sessionCommits > 0) {
    print.row('Commits', `${state.sessionCommits} this session`);
  }

  if (state.lastCommittedAt) {
    const fileLabel = state.lastCommittedFile ? `  (${state.lastCommittedFile})` : '';
    print.row('Last commit', `${timeAgo(state.lastCommittedAt)}${fileLabel}`);
  }

  if (state.lastPushedAt) {
    print.row('Last push', timeAgo(state.lastPushedAt));
  }

  if (resumedAfterSleep && state.catchUpCommits > 0) {
    print.gap();
    print.good(`${state.catchUpCommits} file${state.catchUpCommits !== 1 ? 's' : ''} committed on wake.`);
  }

  print.gap();
}
