import { readFile } from 'fs/promises';
import boxen from 'boxen';
import chalk from 'chalk';
import { print, timeAgo, TEAL, PINK } from '../ui.js';
import { PID_FILE } from '../paths.js';
import { readState, STATE } from '../state.js';
import { loadGlobalConfig, globalConfigExists } from '../settings.js';

// ─── helpers ──────────────────────────────────────────────────────────────────

async function getLivePid() {
  try {
    const raw = await readFile(PID_FILE, 'utf8');
    const pid = parseInt(raw.trim(), 10);
    process.kill(pid, 0);
    return pid;
  } catch {
    return null;
  }
}

function formatUptime(startedAt) {
  if (!startedAt) return 'Unknown';
  const seconds = Math.floor((Date.now() - new Date(startedAt)) / 1000);
  if (seconds < 60)   return `${seconds}s`;
  if (seconds < 3600) return `${Math.floor(seconds / 60)}m`;
  return `${Math.floor(seconds / 3600)}h ${Math.floor((seconds % 3600) / 60)}m`;
}

// left-padded label + white value — used inside the box
function row(label, value) {
  return chalk.dim(`  ${label.padEnd(13)}`) + chalk.white(value);
}

// ─── boxen options ────────────────────────────────────────────────────────────

const BOX_OPTS = {
  padding:     { top: 0, bottom: 0, left: 1, right: 2 },
  borderStyle: 'round',
  borderColor: TEAL,
};

const BOX_OPTS_PINK = {
  padding:     { top: 0, bottom: 0, left: 1, right: 2 },
  borderStyle: 'round',
  borderColor: PINK,
};

// ─── main ─────────────────────────────────────────────────────────────────────

export async function status() {
  if (!(await globalConfigExists())) {
    print.gap();
    print.brand('gitwrit is not set up.');
    print.hint('Run gitwrit init to get started.');
    print.gap();
    return;
  }

  const pid    = await getLivePid();
  const state  = await readState();
  const config = await loadGlobalConfig();

  print.gap();

  // ── not running ─────────────────────────────────────────────────────────────

  if (!pid) {
    if (state.status === STATE.PAUSED) {
      const lines = [
        '',
        chalk.hex(PINK).bold('  gitwrit is paused.'),
        '',
        chalk.dim(`  Last active ${timeAgo(state.pausedAt)}.`),
        chalk.dim('  Run gitwrit start to resume watching.'),
        '',
      ];
      console.log(boxen(lines.join('\n'), BOX_OPTS_PINK));
    } else {
      const lines = [
        '',
        chalk.dim('  gitwrit is not running.'),
        '',
        chalk.dim('  Run gitwrit start to begin watching.'),
        '',
      ];
      console.log(boxen(lines.join('\n'), { ...BOX_OPTS, borderColor: 'gray' }));
    }
    print.gap();
    return;
  }

  // ── running ──────────────────────────────────────────────────────────────────

  const resumedAfterSleep = state.resumedAt &&
    (Date.now() - new Date(state.resumedAt)) < 60000;

  const lines = [''];

  if (resumedAfterSleep) {
    lines.push(chalk.hex(TEAL).bold('  gitwrit is running') + chalk.dim(' — resumed after sleep.'));
  } else {
    lines.push(chalk.hex(TEAL).bold('  gitwrit is running.'));
  }

  lines.push('');
  lines.push(row('Uptime',   formatUptime(state.startedAt)));
  lines.push(row('Watching', config.watch.map(w => w.path).join(', ')));

  if (state.sessionBranch) {
    lines.push(row('Branch', state.sessionBranch) + chalk.hex(PINK).dim(' (autogenerated)'));
  } else {
    lines.push(row('Branch', 'Current branch'));
  }

  if (state.sessionCommits > 0) {
    lines.push(row('Commits', `${state.sessionCommits} this session`));
  }

  if (state.lastCommittedAt) {
    const fileLabel = state.lastCommittedFile ? `  (${state.lastCommittedFile})` : '';
    lines.push(row('Last commit', `${timeAgo(state.lastCommittedAt)}${fileLabel}`));
  }

  if (state.lastPushedAt) {
    lines.push(row('Last push', timeAgo(state.lastPushedAt)));
  }

  if (resumedAfterSleep && state.catchUpCommits > 0) {
    lines.push('');
    lines.push(chalk.hex(TEAL)(`  ✔  ${state.catchUpCommits} file${state.catchUpCommits !== 1 ? 's' : ''} committed on wake.`));
  }

  lines.push('');

  console.log(boxen(lines.join('\n'), BOX_OPTS));
  print.gap();
}