import { readFile, writeFile, access } from 'fs/promises';
import { join } from 'path';
import { GLOBAL_CONFIG_FILE, LOCAL_CONFIG_FILENAME } from './paths.js';

// ─── defaults ────────────────────────────────────────────────────────────────

export const DEFAULTS = {
  fileTypes: ['.md', '.mdx'],
  debounce: 3000,        // ms — wait after last save before committing
  pushInterval: 300000,  // ms — time between remote pushes (5 min)
  branchMode: 'current', // 'current' | 'autogenerated'
  watch: [],             // array of { type: 'directory'|'repo', path: string }
};

// ─── existence checks ─────────────────────────────────────────────────────────

export async function globalConfigExists() {
  try {
    await access(GLOBAL_CONFIG_FILE);
    return true;
  } catch {
    return false;
  }
}

export async function localConfigExists(dir) {
  try {
    await access(join(dir, LOCAL_CONFIG_FILENAME));
    return true;
  } catch {
    return false;
  }
}

// ─── loaders ─────────────────────────────────────────────────────────────────

export async function loadGlobalConfig() {
  const raw = await readFile(GLOBAL_CONFIG_FILE, 'utf8');
  return JSON.parse(raw);
}

export async function loadLocalConfig(dir) {
  try {
    const raw = await readFile(join(dir, LOCAL_CONFIG_FILENAME), 'utf8');
    return JSON.parse(raw);
  } catch {
    return null; // null = no local overrides, follow global
  }
}

// ─── writers ──────────────────────────────────────────────────────────────────

export async function saveGlobalConfig(config) {
  await writeFile(GLOBAL_CONFIG_FILE, JSON.stringify(config, null, 2), 'utf8');
}

export async function saveLocalConfig(dir, overrides) {
  const localPath = join(dir, LOCAL_CONFIG_FILENAME);
  await writeFile(localPath, JSON.stringify(overrides, null, 2), 'utf8');
}

// ─── resolver ─────────────────────────────────────────────────────────────────

// merges global config with any local overrides for a given directory.
// local keys win — unset local keys fall through to global.
export async function resolveConfig(dir) {
  const global = await loadGlobalConfig();
  const local = await loadLocalConfig(dir);
  if (!local) return { ...global, _source: 'global' };
  return { ...global, ...local, _source: 'local' };
}

// ─── validation ───────────────────────────────────────────────────────────────

export function validateConfig(config) {
  const errors = [];

  if (!Array.isArray(config.fileTypes) || config.fileTypes.length === 0) {
    errors.push('fileTypes must be a non-empty array (e.g. [".md", ".mdx"])');
  }

  if (typeof config.debounce !== 'number' || config.debounce < 500) {
    errors.push('debounce must be a number >= 500ms');
  }

  if (typeof config.pushInterval !== 'number' || config.pushInterval < 60000) {
    errors.push('pushInterval must be a number >= 60000ms (1 minute)');
  }

  if (!['current', 'autogenerated'].includes(config.branchMode)) {
    errors.push('branchMode must be "current" or "autogenerated"');
  }

  return errors;
}

// ─── watch list helpers ───────────────────────────────────────────────────────

export async function addWatchPath(entry) {
  const config = await loadGlobalConfig();
  const already = config.watch.some(w => w.path === entry.path);
  if (already) return false;
  config.watch.push(entry);
  await saveGlobalConfig(config);
  return true;
}

export async function removeWatchPath(dirPath) {
  const config = await loadGlobalConfig();
  const before = config.watch.length;
  config.watch = config.watch.filter(w => w.path !== dirPath);
  if (config.watch.length === before) return false;
  await saveGlobalConfig(config);
  return true;
}